import json
from langchain_core.messages import HumanMessage
from langgraph.errors import GraphRecursionError
from app.agent.graph import build_graph
from langgraph.checkpoint.memory import MemorySaver
import asyncio

# Initialize in-memory checkpointer as a singleton so it persists across requests
memory_saver = MemorySaver()

async def stream_agent_events(session_id: str, user_input: str):
    """
    Generator function that yields Server-Sent Events (SSE) as the LangGraph agent executes.
    """
    inputs = {"chat_messages": [HumanMessage(content=user_input)]}
    
    config = {
        "configurable": {"thread_id": session_id},
        "recursion_limit": 10
    }
    
    try:
        workflow = build_graph()
        agent_app = workflow.compile(checkpointer=memory_saver)
        
        # We use astream_events to get granular updates (node starts, tool calls, token generation)
        # version="v2" is required for LangGraph >= 0.1
        async for event in agent_app.astream_events(inputs, config=config, version="v2"):
            kind = event["event"]
            
            # Yield when a node starts (e.g., agent_node vs action_node)
            if kind == "on_chain_start" and event.get("name") in ["agent_node", "action_node"]:
                data = json.dumps({"event": "node_start", "node": event["name"]})
                # EventSourceResponse handles formatting, so we just yield the JSON string
                yield data
                
            # Yield when the LLM decides to call a tool
            elif kind == "on_tool_start":
                data = json.dumps({"event": "tool_call", "tool": event["name"]})
                yield data
                
            # Yield individual tokens as they are generated by the LLM
            elif kind == "on_chat_model_stream":
                chunk = event["data"]["chunk"]
                if chunk.content:
                    # Pass the token text to the frontend
                    data = json.dumps({"event": "token", "text": chunk.content})
                    yield data
                    
        # Send a completion event when the graph finishes
        yield "[DONE]"
            
    except GraphRecursionError:
        error_msg = "Agent got stuck in an infinite loop. Aborting."
        yield json.dumps({"event": "error", "text": error_msg})
        yield "[DONE]"
        
    except Exception as e:
        error_msg = f"Server error: {str(e)}"
        yield json.dumps({"event": "error", "text": error_msg})
        yield "[DONE]"
