import json
from typing import List
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from langgraph.errors import GraphRecursionError
from app.agent.graph import build_graph
import asyncio

async def stream_agent_events(session_id: str, messages: List[dict]):
    """
    Generator function that yields Server-Sent Events (SSE) as the LangGraph agent executes.
    """
    langchain_messages = []
    for msg in messages:
        role = msg.get("role")
        content = msg.get("content", "")
        if role == "user":
            langchain_messages.append(HumanMessage(content=content))
        elif role == "agent" or role == "assistant":
            langchain_messages.append(AIMessage(content=content))
        elif role == "system":
            langchain_messages.append(SystemMessage(content=content))
            
    inputs = {"chat_messages": langchain_messages}
    
    config = {
        "configurable": {"thread_id": session_id},
        "recursion_limit": 10
    }
    
    try:
        workflow = build_graph()
        # Compiled without checkpointer so Vercel can run statelessly
        agent_app = workflow.compile()
        
        # We use astream_events to get granular updates (node starts, tool calls, token generation)
        # version="v2" is required for LangGraph >= 0.1
        async for event in agent_app.astream_events(inputs, config=config, version="v2"):
            kind = event["event"]
            
            # Yield when a node starts (e.g., agent_node vs action_node)
            if kind == "on_chain_start" and event.get("name") in ["agent_node", "action_node"]:
                data = json.dumps({"event": "node_start", "node": event["name"]})
                # EventSourceResponse handles formatting, so we just yield the JSON string
                yield data
                
            # Yield when the LLM decides to call a tool
            elif kind == "on_tool_start":
                data = json.dumps({"event": "tool_call", "tool": event["name"]})
                yield data
                
            # Yield individual tokens as they are generated by the LLM
            elif kind == "on_chat_model_stream":
                chunk = event["data"]["chunk"]
                if chunk.content:
                    # Pass the token text to the frontend
                    data = json.dumps({"event": "token", "text": chunk.content})
                    yield data
                    
        # Send a completion event when the graph finishes
        yield "[DONE]"
            
    except GraphRecursionError:
        error_msg = "Agent got stuck in an infinite loop. Aborting."
        yield json.dumps({"event": "error", "text": error_msg})
        yield "[DONE]"
        
    except Exception as e:
        error_msg = f"Server error: {str(e)}"
        yield json.dumps({"event": "error", "text": error_msg})
        yield "[DONE]"
